from tkinter import  *
root=Tk()
def projectmsg(): print("New Project")
def new_file(): print("New File")
def open_msg(): print("You have opened a new file")
def save_msg(): print("Your file is saved")
def settings_msg(): print("File Settings!")
def undomsg(): print("undo")
def redomsg(): print("redo")
def copymsg(): print("Copied")
def pastemsg(): print("Pasted")
def findmsg(): print("Finding")
def replacemsg(): print("Replaced")
def toolmsg(): print("Showing the tools")
def appmsg(): print("Select appearance")
def tymsg(): print("File type information")
def coninfomsg(): print("Context information")
def recmsg(): print("Showing recent files")
def rechangemsg(): print("Showing recently changed files")
def backmsg(): print("Go back")
def fwmsg(): print("Going forward")
def symmsg(): print("Symbol!")
def resymmsg(): print("Related symbol")
def fstrmsg(): print("Showing file structure")
def fpamsg(): print("Showing file path")
def overmsg(): print("Overriding methods")
def implmsg(): print("Implement methods")
def insmsg(): print("Inspect Code")
def codmsg(): print("Clean up the code")
def movdnmsg(): print("to move a line down")
def movupmsg(): print("to move a line up")
my_menu=Menu(root)
root.config(menu=my_menu)
file_sub=Menu(my_menu)
my_menu.add_cascade(label="File",menu=file_sub)
file_sub.add_command(label="New Project", command=projectmsg)
file_sub.add_command(label="New", command=new_file)
file_sub.add_separator()
file_sub.add_command(label="Open", command=open_msg)
file_sub.add_command(label="Save As", command=save_msg)
file_sub.add_separator()
file_sub.add_command(label="Settings", command=settings_msg)
file_sub.add_command(label="Quit", command=quit)
edit_sub=Menu(my_menu)
my_menu.add_cascade(label="Edit", menu=edit_sub)
edit_sub.add_command(label="Undo", command=undomsg)
edit_sub.add_command(label="Redo", command=redomsg)
edit_sub.add_separator()
edit_sub.add_command(label="Copy", command=copymsg)
edit_sub.add_command(label="Paste", command=pastemsg)
edit_sub.add_separator()
edit_sub.add_command(label="Find", command=findmsg)
edit_sub.add_command(label="Replace", command=replacemsg)
view_sub=Menu(my_menu)
my_menu.add_cascade(label="View", menu=view_sub)
view_sub.add_command(label="Tools", command=toolmsg)
view_sub.add_command(label="Appearance", command=appmsg)
view_sub.add_separator()
view_sub.add_command(label="Type info", command=tymsg)
view_sub.add_command(label="Context info", command=coninfomsg)
view_sub.add_separator()
view_sub.add_command(label="Recent Files", command=recmsg)
view_sub.add_command(label="Recently changed files", command=rechangemsg)
nav_sub=Menu(my_menu)
my_menu.add_cascade(label="Navigate", menu=nav_sub)
nav_sub.add_command(label="Back", command=backmsg)
nav_sub.add_command(label="Forward", command=fwmsg)
nav_sub.add_separator()
nav_sub.add_command(label="Symbol", command=symmsg)
nav_sub.add_command(label="Related symbol", command=resymmsg)
nav_sub.add_separator()
nav_sub.add_command(label="File Structure", command=fstrmsg)
nav_sub.add_command(label="File path", command=fpamsg)
code_sub=Menu(my_menu)
my_menu.add_cascade(label="Code", menu=code_sub)
code_sub.add_command(label="Overriding methods", command=overmsg)
code_sub.add_command(label="Implement methods", command=implmsg)
code_sub.add_separator()
code_sub.add_command(label="Inspect method", command=insmsg)
code_sub.add_command(label="Code cleanup", command=codmsg)
code_sub.add_separator()
code_sub.add_command(label="Move Line Down", command=movdnmsg)
code_sub.add_command(label="Move Line Up", command=movupmsg)
tool_bar= Frame(root, bg="black")
butt=Button(tool_bar, text="demo")
butt.pack(side=LEFT, padx=2, pady=2)
tool_bar.pack(side=TOP, fill=X)
status_bar=Label(root, text="This is the demo for status and toolbar", bd=2, relief='sunken')
status_bar.pack(side=BOTTOM, fill=X,)
root.mainloop()