from tkinter import  *
root =Tk()
l_u=Label(root,text="Username:")
l_m=Label(root,text="Mobile number:")
l_e=Label(root,text="e-mail:")
l_a=Label(root,text="Age:")
l_p1=Label(root,text="Enter password:")
l_p2=Label(root,text="Confirm password:")
e_u=Entry(root)
e_m=Entry(root)
e_e=Entry(root)
e_a=Entry(root)
e_p1=Entry(root)
e_p2=Entry(root)
b1=Button(root,text="log in", fg="white", bg="blue" )
b2=Button(root,text="Cancel", fg="white", bg="blue" )
l_u.grid(row=0,column=0)
e_u.grid(row=0,column=1)
l_m.grid(row=1,column=0)
e_m.grid(row=1,column=1)
l_e.grid(row=2,column=0)
e_e.grid(row=2,column=1)
l_a.grid(row=3,column=0)
e_a.grid(row=3,column=1)
l_p1.grid(row=4,column=0)
e_p1.grid(row=4,column=1)
l_p2.grid(row=5,column=0)
e_p2.grid(row=5,column=1)
b1.grid(row=6, column=0)
b2.grid(row=6, column=1)
root.mainloop()

